# Note: this is a development docker compose.yml file used to test dockman with various services
# this is not the recommended way to set up see https://dockman.radn.dev/docs/install/docker#docker-compose to setup dockman with compose
services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - pocket-id-net
    restart: unless-stopped

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:latest
    environment:
      - APP_URL=https://localhost  # The public URL you will use
      - TRUST_PROXY=true           # Required when running behind Caddy
    volumes:
      - pocket_id_data:/app/backend/data
    networks:
      - pocket-id-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  pocket_id_data:

networks:
  pocket-id-net: