# Note: this is a development docker compose.yml file used to test dockman with various services
# this is not the recommended way to set up see https://dockman.radn.dev/docs/install/docker#docker-compose to setup dockman with compose
services:
  dockman:
    container_name: dockman-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKMAN_AUTH_ENABLE: true
      DOCKMAN_AUTH_OIDC_ENABLE: true
      DOCKMAN_AUTH_OIDC_ISSUER: "https://localhost"
      DOCKMAN_AUTH_OIDC_CLIENT_ID: 74347a8e-718d-4bb1-b0f6-e264b0c45bad
      DOCKMAN_AUTH_OIDC_CLIENT_SECRET: DIvLgg09ibXJhmVTtFYQXPjSrzBTJd2D
      DOCKMAN_AUTH_OIDC_REDIRECT_URL: "http://localhost:8866/api/auth/login/oidc/callback"

      DOCKMAN_COMPOSE_ROOT: /home/ra341/Dev/Go/dockman/compose
    volumes:
      - ./dockman/compose:/home/ra341/Dev/Go/dockman/compose
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8221:8866"
    depends_on:
      - pocket-id

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - pocket-id-net
    restart: unless-stopped

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:latest
    environment:
      - ENCRYPTION_KEY=ZLEAiNYTFgxFgSomYSsWGC1xdH1U26Z6sScFHM8gcoM=
      - APP_URL=https://localhost
      - TRUST_PROXY=true
    volumes:
      - ./.build/pocket_id:/app/backend/data
    networks:
      - pocket-id-net
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  pocket_id_data:

networks:
  pocket-id-net: